### Users requests
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/users
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Skills requests
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/skills
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get categories
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/categories
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get subcategories by category id
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/subcategories
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get subcategories by category id
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/subcategories?category_id=in.(766d88d0-9c96-445e-8138-2552a0c4c131)
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get cities
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/cities
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get favorites
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/favorites
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get user_wishes
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/user_wishes
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get notifications
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/notifications
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get genders
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/gender
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU

### Get suggestions
GET https://evenrzibkvwjuhhncpmt.supabase.co/rest/v1/suggestions
Apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZW5yemlia3Z3anVoaG5jcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzAwNzMsImV4cCI6MjA2NjI0NjA3M30.qSDE_4uK6sh6yTr4B2I_ftRhkn2sZTLXDqITSyReZpU